# Generated by Django 6.1 on 2026-08-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mesaage',
            new_name='message',
        ),
    ]
