# Generated by Django 6.1 on 2026-08-13 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skils_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^09\\d{9}$')])),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
