# Generated by Django 6.1 on 2026-08-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
